apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: us-central1-docker.pkg.dev/sit727-24t1-prajapati-f703eee/viraj-docker/node-web
          ports:
            - containerPort: 80
